/**
 * Tradewolf API
 * A definition for Tradewolf API
 *
 * The version of the OpenAPI document: 0.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { DefaultApi } from "./api";
import { BASE_PATH } from "./base";
import { stringify } from "querystring";
import * as crypto from "crypto";
import * as createHmac from "create-hmac"

export * from "./api";
export * from "./configuration";

class TradewolfApi {
    api: DefaultApi
    apiKey: string
    secretKey: string
    utf8_encoder: TextEncoder

    constructor(apiKey: string, secretKey: string) {
        this.api = new DefaultApi({basePath: BASE_PATH})
        this.apiKey = apiKey
        this.secretKey = secretKey
        this.utf8_encoder = new TextEncoder();
    }

    _getApiTimestamp(): number {
        return new Date().getTime() 
    }

    _getQueryHeader(path: string, method:"GET" | "POST", params: any = {}): {X_API_KEY:string,X_API_TIMESTAMP:number, X_API_SIGNATURE:string} {
        const nonce = this._getApiTimestamp()
        const queryString = stringify(params)
        let message = nonce + path + method
        if(method == "POST"){
            message += queryString
        }
        
        const hmac = createHmac("sha256",Buffer.from(this.secretKey))
        const signature = hmac.update(this.utf8_encoder.encode(message)).digest('hex')
        
        const headers = {
            X_API_KEY: this.apiKey,
            X_API_TIMESTAMP: nonce,
            X_API_SIGNATURE: signature            
        }
        return headers
    }

    public getArbitragePairs(): ReturnType<DefaultApi["getArbitragePairs"]> {
        const headers = this._getQueryHeader(`/v1/arbitrage-pairs`,"GET")
        return this.api.getArbitragePairs(headers.X_API_KEY, headers.X_API_SIGNATURE, headers.X_API_TIMESTAMP)
    }

    public getOrderBookByExchange(exchange: string): ReturnType<DefaultApi["getOrderBookByExchange"]> {
        const headers = this._getQueryHeader(`/v1/orderbooks`,"GET", {exchange})
        return this.api.getOrderBookByExchange(exchange,headers.X_API_KEY, headers.X_API_SIGNATURE, headers.X_API_TIMESTAMP)
    }

    public getWithdrawalFeesByExchange(exchange: string): ReturnType<DefaultApi["getWithdrawalFeesByExchange"]> {
        const headers = this._getQueryHeader(`/v1/withdrawal-fees`,"GET",{exchange})
        return this.api.getWithdrawalFeesByExchange(exchange,headers.X_API_KEY, headers.X_API_SIGNATURE, headers.X_API_TIMESTAMP)
    }
}
export default TradewolfApi